### ISSUE TITLE
GCV2hocr not working: no file

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#109]
The transformation GCV2hocr in the Web GUI with the test file https://raw.githubusercontent.com/kba/ocr-fileformat-samples/master/samples/google-cloud/test_picture.json has an error message now: no file. This is unrelated of the PR #106.

**Comment by stweil** [comment]
That conversion also did not handle input from STDIN. Did it ever work with the web interface?

I added a commit to PR #106 which fixes this issue.

**Comment by zuphilip** [comment]
I don't know. That is something a format which I usually don't test. It could be an quite old issue, or maybe some changes in the upstream caused that.
