### ISSUE TITLE
Add hocr__page transformation

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#113]
The transformation alto__page does actually also support hocr input and therefore we can simply use it for the transformation hocr__page as well. One should only need some symlinking and updateing the documentations. But we may want after PR #106 has been integrated to do this.

BTW one can already try this out by using the alto__page transformation on a hocr file, e.g. https://digi.bib.uni-mannheim.de/~stweil/ocr-praxis/0001-tesseract.hocr .

**Comment by stweil** [comment]
Commit cedace708004a6971f6fbfb98ac039e82681a016 (now added to PR #106) should do that.
