### ISSUE TITLE
New Saxon version 10.2 is out

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#124]
We can update to the new Saxon version 9.9.1.7 which is out since some days:

https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/

https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download 

In principle this only means a similar commit like in https://github.com/UB-Mannheim/ocr-fileformat/commit/4faff379843f4923960cbba6cbbd0a741fb4ffe6 but this should be tested then also.

**Comment by zuphilip** [comment]
And the next version on the maior release 10:

https://sourceforge.net/projects/saxon/files/Saxon-HE/10/Java/

https://sourceforge.net/projects/saxon/files/Saxon-HE/10/Java/SaxonHE10-0J.zip/download

**Comment by zuphilip** [comment]
Next is 10.1:

https://sourceforge.net/projects/saxon/files/Saxon-HE/10/Java/SaxonHE10-1J.zip/download

**Comment by zuphilip** [comment]
Next is 10.2:

https://sourceforge.net/projects/saxon/files/Saxon-HE/10/Java/SaxonHE10-2J.zip/download

**Comment by stweil** [comment]
Citation from http://www.saxonica.com/download/java.xml:

> The latest maintenance release of 9.9 is Saxon 9.9.1.7, released on 4 March 2020. Saxon 9.9 is currently considered the most stable and reliable release.

Pull request #127 updates to that version.

**Comment by stweil** [comment]
Meanwhile Saxon 10.6 is the current stable version, so we should update to that version.

**Comment by stweil** [comment]
Pull request #144 updates Saxon to version 10.6, so this issue can be closed as soon as these changes were merged.

**Comment by stweil** [comment]
Now there exists a bug fix release 10.8, and 11.3 is the latest release.

**Comment by stweil** [comment]
10.8 is now used in git master (and 11.x will follow soon), so I close this issue.
