### ISSUE TITLE
alto to text: too many spaces

### ISSUE THREAD

**Issue by jbarth-ubhd** [UB-Mannheim/ocr-fileformat#129]
Example alto excerpt:

```xml
<TextLine><String CONTENT="Wappen:"/><SP/><String CONTENT="Heimstatt;"/><SP/><String CONTENT="Heimstatt,">... ...
```
converts to text
```
Wappen:␣␣Heimstatt;␣␣Heimstatt,␣␣Neipperg,␣␣Gemmingen ... ...
```

**Comment by kba** [comment]
You mean every `<SP/>` results in two spaces, not one?

**Comment by jbarth-ubhd** [comment]
I don't know where the two spaces exactly come from, but there should only 1 I'd say.

**Comment by kba** [comment]
ALTO-to-Text transformation is using @filak's XSLT (https://github.com/filak/hOCR-to-ALTO/blob/master/alto__text.xsl), this needs to be fixed upstream. Can you open an issue there as well pls?

**Comment by jbarth-ubhd** [comment]
opened: https://github.com/filak/hOCR-to-ALTO/issues/22

**Comment by kba** [comment]
fix: https://github.com/mittagessen/kraken-models/pull/5

**Comment by stweil** [comment]
So is this issue fixed and can it be closed?

**Comment by kba** [comment]
> So is this issue fixed and can it be closed?

Yes, it has been fixed. If you have an older installation of ocr-fileformat (before feb 2021), you'll need to re-clone hOCR-to-ALTO:

```
rm vendor/hOCR-to-ALTO
make vendor install
```

(we should really use git submodules to make tracking changes and updating easier)
