### ISSUE TITLE
Transformation for ImageWare MyBib

### ISSUE THREAD

**Issue by karkraeg** [UB-Mannheim/ocr-fileformat#139]
I wrote a conversion script to transform ImageWare MyBib eL OCR to ALTO: https://github.com/karkraeg/im2alto

Example for ImageWare OCR: https://library.fes.de/ddb/vs07100/VS07100_1.xml

Please feel free to use the XSL in your Tool!

**Comment by stweil** [comment]
Thank you! I'm afraid we are currently busy with a lot of other things, so if someone sends a pull request, that would help us.

**Comment by karkraeg** [comment]
I`d be happy to, but the subdirectory XSLT has it that XSL files are ignored:

![grafik](https://user-images.githubusercontent.com/8436596/133559423-7756e634-f5c9-4119-8d0a-16a6093ae13d.png)

Also we would need a corresponding script in https://github.com/UB-Mannheim/ocr-fileformat/tree/master/script/transform correct?

I'll look into it!
