### ISSUE TITLE
page__alto transformation mixes XML with logging in the output

### ISSUE THREAD

**Issue by bertsky** [UB-Mannheim/ocr-fileformat#143]
…resulting in invalid XML of course. Here is the culprit:

https://github.com/UB-Mannheim/ocr-fileformat/blob/d0c78538e35d4cfff23fda0a82a75440f15af0e6/script/transform/page__alto#L18

Since page-to-alto has its own logging (to stdout as well), this will get warnings and errors mixed into the output.

**Comment by stweil** [comment]
@bertsky, can we close this issue?

**Comment by bertsky** [comment]
Yes we can.
