### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by yuvaler1** [UB-Mannheim/ocr-fileformat#173]
**Hi**

**I try to use ocr-fileformat and having some troubles in starting.**

**My steps are :**
git clone https://github.com/UB-Mannheim/ocr-fileformat 
cd .\ocr-fileformat\  
docker build -t welcome-to-docker .   

**I get the following error:**
[+] Building 0.0s (1/1) FINISHED                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 833B                                                                               0.0s
Dockerfile:16
--------------------
  14 |         && apk del git make wget gcc libc-dev
  15 |     # Disable POST upload limit
  16 | >>> sed -i 's,post_max_size = 8M,post_max_size = 0,' /etc/php7/php.ini
  17 |     VOLUME /data
  18 |     WORKDIR /data
--------------------
ERROR: failed to solve: dockerfile parse error on line 16: unknown instruction: sed (did you mean user?)

**I changed this line with chat-gpt help:**
&& sed -i 's,post_max_size = 8M,post_max_size = 0,' /etc/php7/php.ini

**I get the following error:**
Dockerfile:6
--------------------
   5 |     WORKDIR /ocr-fileformat
   6 | >>> RUN apk add --no-cache openjdk8-jre php7 php7-json php7-openssl python3 py-lxml py-future git make ca-certificates wget bash gcc libc-dev \
   7 | >>>     && update-ca-certificates \
   8 | >>>     && make install \
   9 | >>>     && cp docker.config.php web/config.local.php \
  10 | >>>     && sed -i '/^upload_max_filesize/ s/=.*$/= 100M/' /etc/php7/php.ini \
  11 | >>>     && sed -i 's/;extension=php_openssl.dll/extension=php_openssl.dll/' /etc/php7/php.ini \
  12 | >>>     && mv web /ocr-fileformat-web \
  13 | >>>     && rm -rf /ocr-fileformat \
  14 | >>>     && apk del git make wget gcc libc-dev \
  15 | >>>     && sed -i 's,post_max_size = 8M,post_max_size = 0,' /etc/php7/php.ini
  16 |     # Disable POST upload limit
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache openjdk8-jre php7 php7-json php7-openssl python3 py-lxml py-future git make ca-certificates wget bash gcc libc-dev     && update-ca-certificates     && make install     && cp docker.config.php web/config.local.php     && sed -i '/^upload_max_filesize/ s/=.*$/= 100M/' /etc/php7/php.ini     && sed -i 's/;extension=php_openssl.dll/extension=php_openssl.dll/' /etc/php7/php.ini     && mv web /ocr-fileformat-web     && rm -rf /ocr-fileformat     && apk del git make wget gcc libc-dev     && sed -i 's,post_max_size = 8M,post_max_size = 0,' /etc/php7/php.ini" did not complete successfully: exit code: 4

**Do you have updated docker file, or do I miss something?**

Thanks,
Yuval

**Comment by stweil** [comment]
@yuvaler1, thank you for your report. The issue should be fixed now.
