### ISSUE TITLE
Broken badge on repo

### ISSUE THREAD

**Issue by mhucka** [UB-Mannheim/ocr-fileformat#178]
Just wanted to mention that the first badge in the README on this repo is showing up as broken.

<kbd>
<img width="779" alt="image" src="https://github.com/UB-Mannheim/ocr-fileformat/assets/1450019/f577cc28-8066-4506-b08c-559f2eaf225a">
</kbd>

**Comment by stweil** [comment]
Codacy required an update to create the badge again, and the code changed:

[![Codacy Badge](https://app.codacy.com/project/badge/Grade/1cd1dc54634249aebbe3e157569ed26f)](https://app.codacy.com/gh/UB-Mannheim/ocr-fileformat/dashboard?utm_source=gh&utm_medium=referral&utm_content=&utm_campaign=Badge_grade)

**Comment by stweil** [comment]
Thank you, this is fixed now.
