### ISSUE TITLE
page to hocr: cr_carea vs ocr_carea

### ISSUE THREAD

**Issue by jbarth-ubhd** [UB-Mannheim/ocr-fileformat#183]
When converting OCR-D *.PAGE.xml to .hocr, I'll get different 2 types of `<div>` classes:

```
jb@pers109:/digitalisate2/PoCoTo/duerer1527--von-run-6/ocr> fgrep -h cr_carea *|sed 's/title=.*//'|sort|uniq -c
    564          <div class="cr_carea" 
    965          <div class="ocr_carea" 
```

**Comment by jbarth-ubhd** [comment]
oops perhaps old version:

-rwxr-xr-x 1 root root 3007 Jan 18  2022 /usr/local/bin/ocr-transform

**Comment by jbarth-ubhd** [comment]
`make all` & `make install` are complaining about missing `JPageConverter 1.5.06` ; this helped:

```
root@pers16:/home/jb/ocr-fileformat/vendor# cp -a JPageConverter\ 1.5 "JPageConverter 1.5.06"
```

**Comment by jbarth-ubhd** [comment]
Did `git pull && make && make install` (with circumventing `JPageConverter 1.5.06`, see above),

same problem:
```
jb@pers109:/home/jb/ocr-fileformat# ocr-transform --version
ocr-transform v0.6.0-11-gee488dd
```

**Comment by jbarth-ubhd** [comment]
@stweil perhaps something is going wrong with `JPageConverter` (see above)

```
commit 63de5ae7ae0f91365d16e77e1f3bd468eb819054
    Use fixed JPageConverter 1.5.06 from UB-Mannheim
```

**Comment by stweil** [comment]
I cannot reproduce the issue:
```
ocr-transform page hocr vendor/page-to-alto/tests/data/OCR-D-OCR-TESS_00001.xml  | fgrep -h cr_carea | sed 's/title=.*//' | sort | uniq -c
     31          <div class="ocr_carea" 
```

**Comment by stweil** [comment]
Try `git status`. Are all submodules up-to-date?

**Comment by jbarth-ubhd** [comment]
```
root@pers109:/home/jb/ocr-fileformat# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by jbarth-ubhd** [comment]
Example:
https://digi.ub.uni-heidelberg.de/diglitData/v/duerer1527_-_aa.PAGE.xml

```
root@pers109:/dwork/ocr/duerer1527/run-6# /usr/local/bin/ocr-transform page hocr duerer1527_-_aa.PAGE.xml  |grep '"cr_'
         <div class="cr_carea" title="bbox 144 141 554 189">
```

**Comment by jbarth-ubhd** [comment]
did `rm -rf ... ; git clone ... ; make all ; make install` - problem still there.

**Comment by jbarth-ubhd** [comment]
additionally did a `git checkout v0.6.0` - but then `make all` complains `... AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by stweil** [comment]
It's a feature. Image regions and graphic regions get `cr_carea` while text regions get `ocr_carea` (see [code](https://github.com/OCR-D/format-converters/blob/fa8b4b54d20ec1b136dad355c213fda94e8878b5/page2hocr.xsl#L59)).

**Comment by jbarth-ubhd** [comment]
Thanks! Looked like a typo.
