### ISSUE TITLE
Conversion to ALTO-2.0 is invalid

### ISSUE THREAD

**Issue by FoxKyong** [UB-Mannheim/ocr-fileformat#26]
I tried conversion from hOCR to ALTO-2.0 and after that when I tried ocr-validate on that file I got:

```
mXSDFilename: /usr/local/share/ocr-fileformat/xsd/alto-2-0.xsd
mXMLFilename: /data/000144300/060.alto
/data/000144300/060.alto fails to validate because: 

cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '([a-zA-Z]{1,8})(-[a-zA-Z0-9]{1,8})*' for type 'language'.
At: 1:934
```

I also tried to convert it to other versions of ALTO but that all failed but it was just for testing because I need version 2.0.

**Comment by stweil** [comment]
Which hOCR did you use for that test? Could you please add it here to allow reproducing the problem?

**Comment by FoxKyong** [comment]
I have attached the file. But the same problem is caused by every hOCR I tried to convert. hOCR is created by Tesseract v3.04.01.
[060.hocr.zip](https://github.com/UB-Mannheim/ocr-fileformat/files/461130/060.hocr.zip)

**Comment by kba** [comment]
Thanks for trying @FoxKyong and for asking for ALTO support in tesseract.

Problem is in https://github.com/kba/hOCR-to-ALTO/, I'll look into it.

**Comment by kba** [comment]
The problem was with mapping language. Should be fixed in https://github.com/kba/hOCR-to-ALTO/issues/1. Can you try

```
(cd vendor/hOCR-to-ALTO; git pull)
```

and try the transformation/validation again?

**Comment by FoxKyong** [comment]
I have tried it and it works. Thanks.
