### ISSUE TITLE
Activate automatic docker builds

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#32]
I suggest that we just do this, or is there any reason to wait?

**Comment by kba** [comment]
They are active but builds have been failing for a while (e.g. https://hub.docker.com/r/kbai/ocr-fileformat/builds/bu4tmu33knd353zrgpugmwl/) because of an issue with alpine's unzip. Will look into it.

**Comment by zuphilip** [comment]
I would also suggest to move them to https://hub.docker.com/r/ubma/ocr-fileformat/, i.e. activated them here at [UB-Mannheim/ocr-fileformat](https://github.com/UB-Mannheim/ocr-fileformat/).

**Comment by kba** [comment]
Active.
