### ISSUE TITLE
hocr to alto not working

### ISSUE THREAD

**Issue by jmokoistinen** [UB-Mannheim/ocr-fileformat#38]
Any ideas what i am missing?

```
ocr-fileformat/example$ ../bin/ocr-transform.sh hocr alto3.0 wetzel_reisebegleiter_1901_0021.hocr res.alto 
[ERROR] No mapping from 'hocr'
Usage: ocr-transform.sh [-dhL] <from> <to> [<infile> [<outfile>]] [-- <script-args>]

    Options:
        --help   -h      Show this help
        --debug  -d      Increase debug level by 1, can be repeated
        --list   -L      List transformations

    Transformations:
        alto2.0 alto3.0

    Saxon options:
```

**Comment by kba** [comment]
You need to download the scripts and helpers for transformation/validation. In the root folder of the repo either run `sudo make install` to download assets and install to `/usr/local` (so the scripts will be available as `ocr-validate` and `ocr-transform` or run `make vendor` to only download the assets without installation.
