### ISSUE TITLE
Check whether we can switch to official hOCR-to-ALTO fork

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#42]
Currently, we are using our [own fork](https://github.com/kba/hOCR-to-ALTO) for the hOCR-to-ALTO, but the differences could be now already integrated in the [official fork](https://github.com/filak/hOCR-to-ALTO). Can we switch here to the official fork now?

**Comment by kba** [comment]
Yes, @filak merged our changes, can be switched to upstream repo.

**Comment by zuphilip** [comment]
Done with https://github.com/UB-Mannheim/ocr-fileformat/commit/2f3824d36eb9d59c3fd8e7cc55872e3cf8e2ab4a
