### ISSUE TITLE
Support conversion from and to PAGE XML

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/ocr-fileformat#79]
This will be required for the OCR-D workflow. Note that OCR-D plans to extend the current PAGE XML standard.

**Comment by zuphilip** [comment]
1) Can you organize some examples of PAGE XML files which we can use as good test cases and freely share e.g. in https://github.com/kba/ocr-fileformat-samples ?

2) We can start with simple conversions as PAGE XML to text, cf. https://github.com/cneud/page-to-text/blob/master/page_to_text.py by @cneud , but I would prefer a XSLT solution for this.

3) Any free mapping information from or to PAGE XML format would be helpful.

**Comment by zuphilip** [comment]
de1f2bb3d1ff04c719c6e084fe3c85450608f4c4 introduced a PAGE to hocr support.

**Comment by zuphilip** [comment]
There is a simple example PAGE XML file https://github.com/PRImA-Research-Lab/PAGE-XML/blob/master/documentation/example/SimplePage.xml and a more advanced one https://github.com/PRImA-Research-Lab/PAGE-XML/blob/master/pagecontent/examples/aletheiaexamplepage.xml . I created with these two test files a XSLT transformation for PAGE to text, see PR #91.

**Comment by zuphilip** [comment]
See #97, #100, #106.
