### ISSUE TITLE
Support ALTO 4.0

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#81]
The new version ALTO 4.0 was recently released: https://github.com/altoxml/documentation/wiki/v4.0-Changes and any support here would be great. The validation with the XSD http://www.loc.gov/standards/alto/v4/alto-4-0.xsd should be straight forward to do. CC @cneud

**Comment by cneud** [comment]
Super quick reaction...but maybe too quick 😄 
It seems there has been a little bit of confusion with both https://www.loc.gov/standards/alto/v4/alto.xsd and https://github.com/altoxml/schema/blob/master/v4/alto-4-0.xsd still containing the "draft" remark and wrong release date in the header section. Will clarify and rectify with the board members asap!

**Comment by kba** [comment]
Validation will be up-to-date with the upstream ALTO schema repo if you build from source.

I can prepare a new release with tarball including ALTO 4 xsd once it's ready for distribution.

**Comment by zuphilip** [comment]
Would now be a good point to make a new release including ALTO 4.0?

**Comment by cneud** [comment]
From an ALTO point of view, the [release 4.1](https://github.com/altoxml/documentation/wiki/Versions) fixed a few bugs with v4.0 and can be considered fairly stable.

**Comment by zuphilip** [comment]
With [v0.3.0](https://github.com/UB-Mannheim/ocr-fileformat/releases/tag/v0.3.0) we support now validation of ALTO 4.0 and 4.1 as well as transformations from and to the new ALTO versions. Thus, I would say that we can close this issue now. However, note that AFAIK we are treating the different ALTO versions more or less the same. If any new feature of ALTO 4.0 or 4.1 would be interesting to support in any transformation, then I suggest to open a new specific issue about this.
