### ISSUE TITLE
No text from OCRopy hOCR

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/ocr-fileformat#85]
The following hOCR was created using OCRopy. `ocr-transform` finds no text for conversion to text or alto2.0.

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
    <title>OCR Results</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="ocr-system" content="ocropy-1.3.3" />
    <meta name="ocr-capabilities" content="ocr_line ocr_page" />
    </head>
    <body>

    <div class='ocr_page' title='image 0007.bin.png; bbox 0 0 1600 2800'>
    <span class='ocr_line' title='bbox 171 452 577 545'>Teufels</span><br />
    <span class='ocr_line' title='bbox 275 891 581 960'>natürliche</span><br />
    <p />
    <span class='ocr_line' title='bbox 628 333 719 378'>Des</span><br />
    <span class='ocr_line' title='bbox 670 450 1188 548'>Lustschloß.</span><br />
    <span class='ocr_line' title='bbox 640 774 733 822'>Elne</span><br />
    <span class='ocr_line' title='bbox 635 889 1095 961'>Zauber - Oper</span><br />
    <span class='ocr_line' title='bbox 490 1024 944 1093'>in drey Akten</span><br />
    <span class='ocr_line' title='bbox 506 1278 725 1325'>von</span><br />
    <span class='ocr_line' title='bbox 333 1391 1018 1462'>August von Kotzebue.</span><br />
    <span class='ocr_line' title='bbox 528 2131 945 2194'>Leipzi gs</span><br />
    <span class='ocr_line' title='bbox 302 2209 1097 2292'>bep Pauk Gotthelf Kun ntgr-</span><br />
    <span class='ocr_line' title='bbox 627 2312 869 2347'>L8e1.</span><br />
    </div>
    </body>
    </html>

**Comment by zuphilip** [comment]
There are no child elements for `ocr_line` except the textnode itself. This is different to the output of Tesseract, where https://github.com/filak/hOCR-to-ALTO is specialized. However, it might be enough to change:

```diff
- <xsl:template match="*">
+ <xsl:template match="node()">
```

in https://github.com/filak/hOCR-to-ALTO/blob/f05740cb71a162587027936934d4c6a16a2898df/hocr2text.xsl#L36 . Or possibly some more changes then. Anyway, it has to fixed in the upstream repository.

**Comment by zuphilip** [comment]
This was fixed in the upstream repo. @stweil Can you check that this fix solves the issue?

(Then, we might just need to trigger a new Docker build to fix this here.)

**Comment by stweil** [comment]
The conversions from hOCR to Alto still need a similar fix. Maybe I can test that later and send a pull request.

**Comment by zuphilip** [comment]
The PR https://github.com/filak/hOCR-to-ALTO/pull/12 should handle the hocr2alto transformations as well.
