### ISSUE TITLE
Show version info in command line

### ISSUE THREAD

**Issue by TuulaP** [UB-Mannheim/ocr-fileformat#87]
In order to add the software versions in use to the documentation of a project, it would be nice if e.g. the usage help of ocr-transform would also show the version information of the software itself.

(I'll keep searching if I can find it somewhere hidden).  Thank you!

**Comment by stweil** [comment]
@TuulaP, the command line now supported `--version` to show the software version.
Can we close this issue?

**Comment by zuphilip** [comment]
Oh, yes let us close it now. I can confirm that it works for me.

@TuulaP If the problem remains, then feel free to reopen it.
